Entry Cameras for the Spawn Point Modifier
H-uru/korman pull request #395
Opened 2024-01-13 19:32 UTC by Hoikas

This simplies the creation of "entry cameras" as seen in Doobes' Ages Veelay and Chiso. In Doobes' Ages, the entry cameras are pushed by entering into a region around the spawn point. When exiting the region, the camera is popped off and the region is disabled. Unfortunately, since this is a general purpose modifier, we cannot simply use that approach. That approach assumes there is a single spawn point for the entire Age. If you were to enter a second spawn point, then walk intgo the other spawn point's entry camera region, it would be spuriously triggered. Therefore, I have written a new `xEntryCam.py` script for CWE to ensure that all entry cameras are disabled when the local player finishes linking in.

2024-01-14 03:32 UTC, Deledrius requested changes

2024-01-14 03:32 UTC, Deledrius commented on korman/exporter/utils.py
> +    """Create a rectangular prisim region object"""
```suggestion
    """Create a rectangular prism region object"""
```

2024-01-14 22:33 UTC, Deledrius approved these changes

2024-02-05 00:40 UTC, Hoikas commented
`xEntryCam.py` is now available in the offline KI and Plasma repos, so I'm merging this.

2024-02-05 00:40 UTC, merged